name: Master
on: 
  push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src/architectit.web
    strategy:
      matrix:
        node: [ '8' ]
    steps:            
    - uses: actions/checkout@v2    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }} 
    - run: npm install
      working-directory: ${{env.working-directory}}
    - run: npm run build
      working-directory: ${{env.working-directory}}
    - name: Upload website as Artifact
      uses: actions/upload-artifact@v1
      with:
        name: website
        path: ${{env.working-directory}}/dist
  publish:    
    runs-on: ubuntu-latest
    needs: build
    steps:    
    - name: Download website changes
      uses: actions/download-artifact@v1
      with:
        name: website
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}     
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob upload-batch --account-name architectitdev -d '$web' -s website